<?php

namespace Database\Seeders;

use App\Models\CollegeMajor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CollegeMajorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $collegeMajors = [
            [
                'major_name' => 'Teknik Informatika',
                'faculty' => 'Fakultas Teknik', // Atau Fakultas Ilmu Komputer
                'description' => 'Program studi yang mempelajari ilmu komputer, pemrograman, dan teknologi informasi.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Software Engineer, Web Developer, Data Scientist, IT Consultant, System Analyst, Game Developer, AI Specialist',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sistem Informasi',
                'faculty' => 'Fakultas Ilmu Komputer', // Atau Fakultas Teknik
                'description' => 'Program studi yang mempelajari analisis dan desain sistem informasi untuk memecahkan masalah bisnis.',
                'field_of_study' => 'Teknik', // Atau Ilmu Komputer
                'career_prospects' => 'Business Analyst, System Analyst, Database Administrator, IT Project Manager, IT Auditor, ERP Consultant',
                'is_active' => true,
            ],
            [
                'major_name' => 'Manajemen',
                'faculty' => 'Fakultas Ekonomi dan Bisnis',
                'description' => 'Program studi yang mempelajari teori dan praktik mengelola organisasi, sumber daya manusia, dan operasi bisnis.',
                'field_of_study' => 'Ekonomi',
                'career_prospects' => 'Manager, Entrepreneur, Business Consultant, HR Manager, Marketing Executive, Financial Planner, Operations Manager',
                'is_active' => true,
            ],
            [
                'major_name' => 'Akuntansi',
                'faculty' => 'Fakultas Ekonomi dan Bisnis',
                'description' => 'Program studi yang mempelajari pencatatan transaksi keuangan, pelaporan keuangan, dan audit.',
                'field_of_study' => 'Ekonomi',
                'career_prospects' => 'Auditor, Tax Consultant, Financial Analyst, Accountant, Finance Manager, Management Accountant',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kedokteran',
                'faculty' => 'Fakultas Kedokteran',
                'description' => 'Program studi yang mempelajari ilmu tentang kesehatan manusia, diagnosis penyakit, dan pengobatan.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Dokter Umum, Dokter Spesialis, Peneliti Medis, Dosen Kedokteran, Manajer Layanan Kesehatan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Hukum',
                'faculty' => 'Fakultas Hukum',
                'description' => 'Program studi yang mempelajari hukum dan sistem peradilan.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Pengacara, Hakim, Jaksa, Notaris, Konsultan Hukum, Legal Staff, Diplomat',
                'is_active' => true,
            ],
            [
                'major_name' => 'Psikologi',
                'faculty' => 'Fakultas Psikologi',
                'description' => 'Program studi yang mempelajari perilaku dan mental manusia.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Psikolog, Konselor, HR Specialist, Peneliti, Terapis, UX Researcher',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Sipil',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari perencanaan, desain, dan konstruksi infrastruktur.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Civil Engineer, Project Manager, Konsultan Konstruksi, Structural Engineer, Surveyor',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sastra Inggris',
                'faculty' => 'Fakultas Ilmu Budaya',
                'description' => 'Program studi yang mempelajari bahasa, sastra, dan budaya Inggris.',
                'field_of_study' => 'Bahasa dan Sastra',
                'career_prospects' => 'Penerjemah, Editor, Pengajar Bahasa Inggris, Penulis, Jurnalis, Diplomat, Staf Kedutaan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Komunikasi',
                'faculty' => 'Fakultas Ilmu Sosial dan Politik',
                'description' => 'Program studi yang mempelajari teori dan praktik komunikasi dalam berbagai konteks.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Public Relations, Jurnalis, Content Creator, Marketing Communication, Penyiar, Event Organizer, Media Planner',
                'is_active' => true,
            ],
            [
                'major_name' => 'Farmasi',
                'faculty' => 'Fakultas Farmasi',
                'description' => 'Program studi yang mempelajari obat-obatan, mulai dari penemuan, pengembangan, produksi, hingga distribusinya.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Apoteker, Peneliti Farmasi, Quality Control di Industri Obat, Regulator Obat, Clinical Research Associate',
                'is_active' => true,
            ],
            [
                'major_name' => 'Arsitektur',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari desain dan perancangan bangunan serta lingkungan binaan.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Arsitek, Desainer Interior, Urban Planner, Kontraktor, Konsultan Properti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Mesin',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari prinsip-prinsip fisika untuk analisis, desain, manufaktur, dan pemeliharaan sistem mekanik.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Mechanical Engineer, Automotive Engineer, Manufacturing Engineer, Konsultan Teknik, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Elektro',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari konsep, perancangan, pengembangan, dan produksi perangkat listrik dan elektronik.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Electrical Engineer, Control Systems Engineer, Telecommunication Engineer, Power Systems Engineer, Electronics Engineer',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Industri',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari optimalisasi proses dan sistem dalam industri, menggabungkan aspek teknik dan manajemen.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Industrial Engineer, Supply Chain Manager, Quality Assurance Manager, Operations Manager, Konsultan Manajemen',
                'is_active' => true,
            ],
            [
                'major_name' => 'Desain Komunikasi Visual (DKV)',
                'faculty' => 'Fakultas Seni Rupa dan Desain',
                'description' => 'Program studi yang mempelajari konsep komunikasi menggunakan elemen visual, seperti grafis, tipografi, dan ilustrasi.',
                'field_of_study' => 'Seni dan Desain',
                'career_prospects' => 'Graphic Designer, Illustrator, Web Designer, Animator, Creative Director, UI/UX Designer',
                'is_active' => true,
            ],
            [
                'major_name' => 'Pendidikan Guru Sekolah Dasar (PGSD)',
                'faculty' => 'Fakultas Keguruan dan Ilmu Pendidikan',
                'description' => 'Program studi yang mempersiapkan calon guru untuk mengajar di tingkat Sekolah Dasar.',
                'field_of_study' => 'Pendidikan',
                'career_prospects' => 'Guru SD, Pengembang Kurikulum, Konsultan Pendidikan Anak, Penulis Buku Anak',
                'is_active' => true,
            ],
            [
                'major_name' => 'Hubungan Internasional',
                'faculty' => 'Fakultas Ilmu Sosial dan Politik',
                'description' => 'Program studi yang mempelajari interaksi antar negara, organisasi internasional, dan isu-isu global.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Diplomat, Analis Politik Internasional, Jurnalis Internasional, Staf Organisasi Internasional, Konsultan Bisnis Internasional',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Gizi',
                'faculty' => 'Fakultas Kesehatan Masyarakat',
                'description' => 'Program studi yang mempelajari hubungan antara makanan dan kesehatan, serta kebutuhan gizi individu dan masyarakat.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Ahli Gizi, Konsultan Gizi, Dietisien, Peneliti Pangan dan Gizi, Quality Control Industri Makanan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Agribisnis',
                'faculty' => 'Fakultas Pertanian',
                'description' => 'Program studi yang menggabungkan ilmu pertanian dengan manajemen bisnis untuk menghasilkan produk pertanian yang bernilai ekonomi.',
                'field_of_study' => 'Pertanian',
                'career_prospects' => 'Manajer Perkebunan, Konsultan Agribisnis, Pengusaha Produk Pertanian, Analis Pasar Komoditas Pertanian',
                'is_active' => true,
            ],
            [
                'major_name' => 'Statistika',
                'faculty' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam (MIPA)',
                'description' => 'Program studi yang mempelajari pengumpulan, analisis, interpretasi, dan presentasi data.',
                'field_of_study' => 'Sains (MIPA)',
                'career_prospects' => 'Statistisi, Data Analyst, Data Scientist, Aktuaris, Peneliti Pasar, Quality Control Analyst',
                'is_active' => true,
            ],
            [
                'major_name' => 'Matematika',
                'faculty' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam (MIPA)',
                'description' => 'Program studi yang mempelajari struktur, ruang, perubahan, dan kuantitas.',
                'field_of_study' => 'Sains (MIPA)',
                'career_prospects' => 'Matematikawan, Analis Data, Aktuaris, Programmer, Peneliti, Pengajar Matematika',
                'is_active' => true,
            ],
            [
                'major_name' => 'Biologi',
                'faculty' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam (MIPA)',
                'description' => 'Program studi yang mempelajari kehidupan dan organisme hidup, termasuk struktur, fungsi, pertumbuhan, evolusi, dan distribusi.',
                'field_of_study' => 'Sains (MIPA)',
                'career_prospects' => 'Biolog, Peneliti, Analis Laboratorium, Konservasionis, Pengajar Biologi, Ahli Bioteknologi',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kimia',
                'faculty' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam (MIPA)',
                'description' => 'Program studi yang mempelajari komposisi, struktur, sifat, dan perubahan materi.',
                'field_of_study' => 'Sains (MIPA)',
                'career_prospects' => 'Ahli Kimia, Peneliti, Quality Control/Assurance, Analis Laboratorium, Pengajar Kimia, Formulator Produk',
                'is_active' => true,
            ],
            [
                'major_name' => 'Fisika',
                'faculty' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam (MIPA)',
                'description' => 'Program studi yang mempelajari materi, energi, dan interaksinya dalam ruang dan waktu.',
                'field_of_study' => 'Sains (MIPA)',
                'career_prospects' => 'Fisikawan, Peneliti, Analis Data, Pengembang Teknologi, Pengajar Fisika, Ahli Geofisika',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Lingkungan',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang menerapkan prinsip-prinsip ilmu pengetahuan dan teknik untuk meningkatkan kualitas lingkungan.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Konsultan Lingkungan, Spesialis Pengolahan Limbah, Manajer Kesehatan dan Keselamatan Lingkungan (K3L), Peneliti Lingkungan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Keperawatan',
                'faculty' => 'Fakultas Ilmu Keperawatan',
                'description' => 'Program studi yang mempersiapkan tenaga profesional untuk memberikan asuhan keperawatan kepada individu, keluarga, dan masyarakat.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Perawat, Konsultan Keperawatan, Manajer Unit Keperawatan, Peneliti Keperawatan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kesehatan Masyarakat',
                'faculty' => 'Fakultas Kesehatan Masyarakat',
                'description' => 'Program studi yang berfokus pada pencegahan penyakit dan peningkatan kesehatan populasi melalui upaya terorganisir.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Epidemiolog, Penyuluh Kesehatan, Administrator Layanan Kesehatan, Peneliti Kesehatan Masyarakat, Spesialis K3',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sosiologi',
                'faculty' => 'Fakultas Ilmu Sosial dan Politik',
                'description' => 'Program studi yang mempelajari masyarakat, interaksi sosial, struktur sosial, dan perubahan sosial.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Sosiolog, Peneliti Sosial, Analis Kebijakan Sosial, Pekerja Sosial, Jurnalis, Community Development Officer',
                'is_active' => true,
            ],
            [
                'major_name' => 'Antropologi',
                'faculty' => 'Fakultas Ilmu Sosial dan Politik',
                'description' => 'Program studi yang mempelajari manusia, baik dari segi budaya maupun fisik, di masa lalu dan masa kini.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Antropolog, Peneliti Budaya, Kurator Museum, Konsultan Lintas Budaya, Jurnalis Budaya',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Politik',
                'faculty' => 'Fakultas Ilmu Sosial dan Politik',
                'description' => 'Program studi yang mempelajari teori dan praktik politik, sistem pemerintahan, dan perilaku politik.',
                'field_of_study' => 'Sosial Humaniora',
                'career_prospects' => 'Analis Politik, Staf Ahli Parlemen, Konsultan Politik, Peneliti, Jurnalis Politik, Aktivis LSM',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sastra Indonesia',
                'faculty' => 'Fakultas Ilmu Budaya',
                'description' => 'Program studi yang mempelajari bahasa, sastra, dan budaya Indonesia secara mendalam.',
                'field_of_study' => 'Bahasa dan Sastra',
                'career_prospects' => 'Penulis, Editor, Jurnalis, Pengajar Bahasa Indonesia (BIPA), Peneliti Sastra, Kritikus Sastra',
                'is_active' => true,
            ],
            [
                'major_name' => 'Perhotelan dan Pariwisata',
                'faculty' => 'Fakultas Pariwisata',
                'description' => 'Program studi yang mempersiapkan tenaga profesional di bidang perhotelan, manajemen perjalanan, dan industri pariwisata.',
                'field_of_study' => 'Pariwisata',
                'career_prospects' => 'Manajer Hotel, Event Organizer, Travel Agent, Tour Guide, Konsultan Pariwisata, Wirausaha di Bidang Pariwisata',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknologi Pangan',
                'faculty' => 'Fakultas Teknologi Pertanian',
                'description' => 'Program studi yang menerapkan ilmu pengetahuan dan teknologi untuk pengolahan, pengawetan, pengemasan, dan distribusi produk pangan.',
                'field_of_study' => 'Pertanian',
                'career_prospects' => 'Ahli Teknologi Pangan, Quality Control Makanan, Peneliti Pangan, Pengembang Produk Makanan, Konsultan Industri Pangan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kedokteran Gigi',
                'faculty' => 'Fakultas Kedokteran Gigi',
                'description' => 'Program studi yang mempelajari kesehatan gigi dan mulut, pencegahan, diagnosis, dan pengobatan penyakit gigi dan mulut.',
                'field_of_study' => 'Kesehatan',
                'career_prospects' => 'Dokter Gigi, Spesialis Ortodonti, Spesialis Bedah Mulut, Peneliti Kesehatan Gigi, Dosen Kedokteran Gigi',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Perminyakan',
                'faculty' => 'Fakultas Teknik Pertambangan dan Perminyakan',
                'description' => 'Program studi yang berfokus pada eksplorasi, pengeboran, produksi, dan pengelolaan sumber daya minyak dan gas bumi.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Reservoir Engineer, Drilling Engineer, Production Engineer, Analis Industri Migas, Konsultan Energi',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Pertambangan',
                'faculty' => 'Fakultas Teknik Pertambangan dan Perminyakan',
                'description' => 'Program studi yang mempelajari eksplorasi, eksploitasi, dan pengolahan bahan galian atau sumber daya mineral.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Mining Engineer, Geotechnical Engineer, Konsultan Pertambangan, Manajer Tambang, Spesialis Lingkungan Tambang',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknik Geologi',
                'faculty' => 'Fakultas Teknik',
                'description' => 'Program studi yang mempelajari komposisi bumi, struktur, sifat fisik, sejarah, dan proses pembentukannya.',
                'field_of_study' => 'Teknik',
                'career_prospects' => 'Geologist, Ahli Geofisika, Konsultan Mitigasi Bencana, Peneliti Sumber Daya Alam, Hidrogeolog',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Kelautan',
                'faculty' => 'Fakultas Perikanan dan Ilmu Kelautan',
                'description' => 'Program studi yang mempelajari aspek fisik, kimia, biologi, dan geologi laut serta pemanfaatan sumber daya laut.',
                'field_of_study' => 'Sains Kelautan',
                'career_prospects' => 'Oceanografer, Peneliti Kelautan, Konsultan Lingkungan Laut, Manajer Kawasan Konservasi Laut, Ahli Bioteknologi Kelautan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Administrasi Bisnis/Niaga',
                'faculty' => 'Fakultas Ilmu Administrasi',
                'description' => 'Program studi yang mempelajari pengelolaan organisasi bisnis secara menyeluruh, mencakup pemasaran, keuangan, SDM, dan operasi.',
                'field_of_study' => 'Ekonomi',
                'career_prospects' => 'Manajer Operasional, Analis Bisnis, Spesialis Pemasaran, Manajer SDM, Wirausahawan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Pendidikan Bahasa Inggris',
                'faculty' => 'Fakultas Keguruan dan Ilmu Pendidikan',
                'description' => 'Program studi yang mempersiapkan calon guru untuk mengajar Bahasa Inggris di berbagai jenjang pendidikan.',
                'field_of_study' => 'Pendidikan',
                'career_prospects' => 'Guru Bahasa Inggris, Pengembang Kurikulum Bahasa Inggris, Penerjemah, Tutor Bahasa Inggris, Pemilik Lembaga Kursus',
                'is_active' => true,
            ],
        ];

        foreach ($collegeMajors as $major)
        {
            CollegeMajor::updateOrCreate(['major_name' => $major['major_name']], $major);
        }
    }
}
