<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universities = [
            [
                'name' => 'Universitas Indonesia',
                'status' => 'negeri',
                'city' => 'Depok',
                'province' => 'Jawa Barat',
                'description' => 'Universitas terkemuka di Indonesia yang didirikan pada tahun 1849.',
                'website' => 'https://www.ui.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/2/2e/UI_paritr%C4%81%E1%B9%87-logo.svg/1200px-UI_paritr%C4%81%E1%B9%87-logo.svg.png',
                'rating' => 4.8,
                'is_active' => true,
            ],
            [
                'name' => 'Institut Teknologi Bandung',
                'status' => 'negeri',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Perguruan tinggi teknik tertua dan terkemuka di Indonesia, didirikan pada tahun 1920.',
                'website' => 'https://www.itb.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/8/8b/Logo_ITB.svg/1200px-Logo_ITB.svg.png',
                'rating' => 4.7,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Gadjah Mada',
                'status' => 'negeri',
                'city' => 'Yogyakarta',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Universitas negeri tertua dan salah satu yang terbesar di Indonesia, didirikan pada tahun 1949.',
                'website' => 'https://www.ugm.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/a/ad/Logo_UGM.svg/1200px-Logo_UGM.svg.png',
                'rating' => 4.7,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Airlangga',
                'status' => 'negeri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Salah satu universitas negeri terkemuka di Indonesia, didirikan pada tahun 1954.',
                'website' => 'https://www.unair.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/3/3d/Lambang_Universitas_Airlangga.svg/1200px-Lambang_Universitas_Airlangga.svg.png',
                'rating' => 4.6,
                'is_active' => true,
            ],
            [
                'name' => 'IPB University',
                'status' => 'negeri',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'description' => 'Perguruan tinggi pertanian terkemuka di Indonesia, didirikan pada tahun 1963.',
                'website' => 'https://www.ipb.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/1/13/Logo_IPB.svg/1200px-Logo_IPB.svg.png',
                'rating' => 4.6,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Diponegoro',
                'status' => 'negeri',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'description' => 'Universitas negeri di Jawa Tengah yang didirikan pada tahun 1957.',
                'website' => 'https://www.undip.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/9/91/Logo_UNDIP.svg/1200px-Logo_UNDIP.svg.png',
                'rating' => 4.5,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Padjadjaran',
                'status' => 'negeri',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Universitas negeri yang didirikan pada tahun 1957 di Bandung.',
                'website' => 'https://www.unpad.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/b/b9/Logo_Universitas_Padjadjaran.svg/1200px-Logo_Universitas_Padjadjaran.svg.png',
                'rating' => 4.5,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Brawijaya',
                'status' => 'negeri',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'description' => 'Universitas negeri terkemuka di Malang, Jawa Timur, didirikan pada tahun 1963.',
                'website' => 'https://www.ub.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c8/Lambang_Universitas_Brawijaya.svg/1200px-Lambang_Universitas_Brawijaya.svg.png',
                'rating' => 4.4,
                'is_active' => true,
            ],
            [
                'name' => 'Institut Teknologi Sepuluh Nopember',
                'status' => 'negeri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Perguruan tinggi teknik terkemuka di Surabaya, didirikan pada tahun 1957.',
                'website' => 'https://www.its.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/1/1b/Logo_ITS.svg/1200px-Logo_ITS.svg.png',
                'rating' => 4.4,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Sebelas Maret',
                'status' => 'negeri',
                'city' => 'Surakarta',
                'province' => 'Jawa Tengah',
                'description' => 'Universitas negeri di Surakarta (Solo), didirikan pada tahun 1976.',
                'website' => 'https://www.uns.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/a/a0/Logo_UNS.png/1200px-Logo_UNS.png',
                'rating' => 4.3,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Hasanuddin',
                'status' => 'negeri',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'description' => 'Universitas negeri terbesar dan terkemuka di Indonesia Timur, didirikan pada tahun 1956.',
                'website' => 'https://www.unhas.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/3/39/Logo_Universitas_Hasanuddin.svg/1200px-Logo_Universitas_Hasanuddin.svg.png',
                'rating' => 4.3,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Bina Nusantara',
                'status' => 'swasta',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'description' => 'Universitas swasta terkemuka di Indonesia yang fokus pada teknologi informasi dan bisnis.',
                'website' => 'https://www.binus.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/e/e9/Logo_Binus.svg/1200px-Logo_Binus.svg.png',
                'rating' => 4.3,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Telkom',
                'status' => 'swasta',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Universitas swasta yang fokus pada bidang ICT, didirikan pada tahun 2013.',
                'website' => 'https://www.telkomuniversity.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/f/fa/Logo_Telkom_University_potrait.svg/1200px-Logo_Telkom_University_potrait.svg.png',
                'rating' => 4.2,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Pendidikan Indonesia',
                'status' => 'negeri',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Perguruan tinggi negeri yang fokus pada pendidikan dan keguruan, didirikan pada tahun 1954.',
                'website' => 'https://www.upi.edu',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/1/19/Logo_UPI.svg/1200px-Logo_UPI.svg.png',
                'rating' => 4.2,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Sumatera Utara',
                'status' => 'negeri',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'description' => 'Universitas negeri tertua di Pulau Sumatera, didirikan pada tahun 1952.',
                'website' => 'https://www.usu.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/a/a1/Logo_Universitas_Sumatera_Utara.png/1200px-Logo_Universitas_Sumatera_Utara.png',
                'rating' => 4.1,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Negeri Yogyakarta',
                'status' => 'negeri',
                'city' => 'Yogyakarta',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Perguruan tinggi negeri yang fokus pada pendidikan dan keguruan, didirikan pada tahun 1964.',
                'website' => 'https://www.uny.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/d/df/Logo_UNY.svg/1200px-Logo_UNY.svg.png',
                'rating' => 4.1,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Islam Indonesia',
                'status' => 'swasta',
                'city' => 'Sleman',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Perguruan tinggi swasta nasional tertua di Indonesia, didirikan pada tahun 1945.',
                'website' => 'https://www.uii.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/0/08/Logo_UII.svg/1200px-Logo_UII.svg.png',
                'rating' => 4.1,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Atma Jaya Yogyakarta',
                'status' => 'swasta',
                'city' => 'Sleman',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Universitas swasta Katolik terkemuka di Yogyakarta, didirikan pada tahun 1965.',
                'website' => 'https://www.uajy.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c3/Logo_UAJY.png/1032px-Logo_UAJY.png',
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Pelita Harapan',
                'status' => 'swasta',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'description' => 'Universitas swasta Kristen yang didirikan pada tahun 1994, dengan berbagai program studi.',
                'website' => 'https://www.uph.edu',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/8/89/Logo_UPH.svg/1200px-Logo_UPH.svg.png',
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Muhammadiyah Yogyakarta',
                'status' => 'swasta',
                'city' => 'Bantul',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Salah satu perguruan tinggi Muhammadiyah terkemuka, didirikan pada tahun 1981.',
                'website' => 'https://www.umy.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/b/b2/Logo_UMY.svg/1200px-Logo_UMY.svg.png',
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Andalas',
                'status' => 'negeri',
                'city' => 'Padang',
                'province' => 'Sumatera Barat',
                'description' => 'Universitas negeri tertua di luar Pulau Jawa, didirikan pada tahun 1955.',
                'website' => 'https://www.unand.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/cf/Logo_Unand.png/1200px-Logo_Unand.png',
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Katolik Parahyangan',
                'status' => 'swasta',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Salah satu universitas swasta tertua di Indonesia, didirikan pada tahun 1955.',
                'website' => 'https://www.unpar.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c7/Logo_UNPAR.png/1021px-Logo_UNPAR.png',
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Negeri Malang',
                'status' => 'negeri',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'description' => 'Perguruan tinggi negeri yang awalnya berfokus pada pendidikan guru, didirikan pada tahun 1954.',
                'website' => 'https://www.um.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/a/a5/Lambang_Universitas_Negeri_Malang.png/1200px-Lambang_Universitas_Negeri_Malang.png',
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Politeknik Elektronika Negeri Surabaya',
                'status' => 'negeri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Politeknik negeri unggulan di bidang elektronika dan teknologi informasi.',
                'website' => 'https://www.pens.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Logo_Politeknik_Elektronika_Negeri_Surabaya.png/1200px-Logo_Politeknik_Elektronika_Negeri_Surabaya.png',
                'rating' => 4.2,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Udayana',
                'status' => 'negeri',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'description' => 'Universitas negeri terbesar dan tertua di Bali, didirikan pada tahun 1962.',
                'website' => 'https://www.unud.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/2/28/Logo_Unud.png/1200px-Logo_Unud.png',
                'rating' => 3.8,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Sriwijaya',
                'status' => 'negeri',
                'city' => 'Palembang',
                'province' => 'Sumatera Selatan',
                'description' => 'Universitas negeri di Sumatera Selatan, didirikan pada tahun 1960.',
                'website' => 'https://www.unsri.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/0/03/Lambang_Unsri.png/1200px-Lambang_Unsri.png',
                'rating' => 3.8,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Kristen Petra',
                'status' => 'swasta',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Universitas swasta Kristen terkemuka di Surabaya, didirikan pada tahun 1961.',
                'website' => 'https://www.petra.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/a/a0/Logo_Universitas_Kristen_Petra.png/900px-Logo_Universitas_Kristen_Petra.png',
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Dian Nuswantoro',
                'status' => 'swasta',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'description' => 'Universitas swasta yang dikenal dengan program studi di bidang teknologi informasi dan komputer.',
                'website' => 'https://www.dinus.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/4/49/Logo_UDINUS.png/1200px-Logo_UDINUS.png',
                'rating' => 3.8,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Mercu Buana',
                'status' => 'swasta',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'description' => 'Universitas swasta dengan beberapa kampus di Jakarta dan sekitarnya.',
                'website' => 'https://www.mercubuana.ac.id',
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/0/05/Logo_UMB.png/1200px-Logo_UMB.png',
                'rating' => 3.8,
                'is_active' => true,
            ],
            // Universitas Tambahan
            [
                'name' => 'Universitas Kristen Maranatha',
                'status' => 'swasta',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Universitas swasta Kristen di Bandung dengan berbagai program studi.',
                'website' => 'https://www.maranatha.edu', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/0/03/Logo_UKM.png/1024px-Logo_UKM.png', // Contoh
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Negeri Semarang',
                'status' => 'negeri',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'description' => 'Universitas negeri di Semarang yang berfokus pada pendidikan dan berbagai ilmu.',
                'website' => 'https://www.unnes.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/9/9e/Logo_UNNES.png/1200px-Logo_UNNES.png', // Contoh
                'rating' => 4.2,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Terbuka',
                'status' => 'negeri',
                'city' => 'Tangerang Selatan', // Kantor Pusat
                'province' => 'Banten', // Kantor Pusat
                'description' => 'Universitas negeri dengan sistem pembelajaran jarak jauh, memiliki UPBJJ di berbagai kota.',
                'website' => 'https://www.ut.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c9/Logo_Universitas_Terbuka.svg/1200px-Logo_Universitas_Terbuka.svg.png', // Contoh
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Bakrie',
                'status' => 'swasta',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'description' => 'Universitas swasta di Jakarta yang didirikan oleh Grup Bakrie.',
                'website' => 'https://www.bakrie.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/6/6b/Logo_Universitas_Bakrie.png/1200px-Logo_Universitas_Bakrie.png', // Contoh
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Ciputra',
                'status' => 'swasta',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Universitas swasta di Surabaya dengan fokus pada entrepreneurship.',
                'website' => 'https://www.ciputra.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/1/18/Logo_Universitas_Ciputra.png/1200px-Logo_Universitas_Ciputra.png', // Contoh
                'rating' => 4.1,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Bunda Mulia',
                'status' => 'swasta',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'description' => 'Universitas swasta di Jakarta dengan fokus pada industri kreatif dan teknologi.',
                'website' => 'https://www.ubm.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/e/e0/Logo_Universitas_Bunda_Mulia.png/1200px-Logo_Universitas_Bunda_Mulia.png', // Contoh
                'rating' => 3.9,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Katolik Widya Mandala Surabaya',
                'status' => 'swasta',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'description' => 'Universitas swasta Katolik di Surabaya dengan berbagai program studi.',
                'website' => 'https://www.ukwms.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/3/34/Logo_UKWMS.png/1200px-Logo_UKWMS.png', // Contoh
                'rating' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Trisakti',
                'status' => 'swasta',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'description' => 'Universitas swasta ternama di Jakarta, dikenal sebagai Kampus Reformasi.',
                'website' => 'https://www.trisakti.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c1/Logo_Universitas_Trisakti.png/1200px-Logo_Universitas_Trisakti.png', // Contoh
                'rating' => 4.1,
                'is_active' => true,
            ],
            [
                'name' => 'UPN Veteran Yogyakarta',
                'status' => 'negeri', // Sudah menjadi PTN
                'city' => 'Sleman',
                'province' => 'D.I. Yogyakarta',
                'description' => 'Universitas Pembangunan Nasional "Veteran" Yogyakarta, perguruan tinggi negeri.',
                'website' => 'https://www.upnyk.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/6/6c/Logo_UPNVY.png/1200px-Logo_UPNVY.png', // Contoh
                'rating' => 4.2,
                'is_active' => true,
            ],
            [
                'name' => 'Politeknik Negeri Bandung',
                'status' => 'negeri',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'description' => 'Politeknik negeri terkemuka di Bandung dengan berbagai program vokasi.',
                'website' => 'https://www.polban.ac.id', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/1/1c/Logo_Polban.svg/1200px-Logo_Polban.svg.png', // Contoh
                'rating' => 4.3,
                'is_active' => true,
            ],
            [
                'name' => 'Universitas Kristen Satya Wacana',
                'status' => 'swasta',
                'city' => 'Salatiga',
                'province' => 'Jawa Tengah',
                'description' => 'Universitas swasta Kristen di Salatiga dengan reputasi yang baik.',
                'website' => 'https://www.uksw.edu', // Contoh
                'logo' => 'https://upload.wikimedia.org/wikipedia/id/thumb/5/5e/Logo_UKSW.png/1200px-Logo_UKSW.png', // Contoh
                'rating' => 4.0,
                'is_active' => true,
            ],
        ];

        foreach ($universities as $university)
        {
            University::updateOrCreate(['name' => $university['name']], $university);
        }
    }
}
